# Generated by Django 2.1.1 on 2018-09-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charitylot',
            old_name='base_cost',
            new_name='minimum_bid',
        ),
        migrations.AddField(
            model_name='charitylot',
            name='image_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='charitylot',
            name='seller',
            field=models.TextField(blank=True),
        ),
    ]
