# Generated by Django 2.1.2 on 2018-10-06 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20180914_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharityBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charity_lot', models.ForeignKey(on_delete=None, related_name='bids', to='api.CharityLot')),
                ('user', models.ForeignKey(on_delete=None, related_name='bids', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
